name: $(Date:yyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - main
pool:
  vmImage: 'windows-latest'
stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'
        failOnAlert: true
    - task: CredScan@2
      inputs:
        toolMajorVersion: 'V2'
    - task: CmdLine@2
      displayName: Install Dependencies
      inputs:
        script: npm install
    - task: CmdLine@2
      displayName: Build
      env:
        NODE_ENV: production
      inputs:
        script: npm run-script build
    - task: CmdLine@2
      displayName: Run Tests and Coverage
      timeoutInMinutes: 20
      inputs:
        script: npm run ci-test
    - task: PublishBuildArtifacts@1
      displayName: 'Upload NPM cache logs'
      inputs:
        pathtoPublish: 'C:\npm\cache\_logs'
        artifactName: 'npm-logs'
      condition: failed()
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: './junit.xml'
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'Unit Tests'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'coverage/cobertura-coverage.xml'
    - task: DeleteFiles@1
      displayName: 'Delete test artifacts'
      inputs:
        SourceFolder: './'
        Contents: |
          junit.xml
          ./coverage
        RemoveSourceFolder: false
    - task: DeleteFiles@1
      displayName: 'Delete coverage files'
      inputs:
        SourceFolder: './coverage'
        Contents: '*'
        RemoveSourceFolder: true
    - task: CopyFiles@2
      displayName: 'Copy AskAway Artifacts to Temp Folder'
      inputs:
        SourceFolder: './'
        Contents: |
          dist/**/*
          package.json
          package-lock.json
          Web.config
        TargetFolder: './temp/'
    - task: CmdLine@2
      displayName: Install Production dependencies
      env:
        NODE_ENV: production
      inputs:
        script: npm install --production
        workingDirectory: ./temp/
    - task: CopyFiles@2
      displayName: 'Copy EV2 Artifacts'
      inputs:
        SourceFolder: './askaway-for-msft/ev2/'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Deployment/'
    - task: ArchiveFiles@2
      displayName: 'Create AskAway.zip'
      inputs:
        rootFolderOrFile: './temp/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/Deployment/bin/AskAway.zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Upload Artifact'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'askaway-for-msft-develop'

