name: $(Date:yyyMMdd)$(Rev:.r)
trigger:
    batch: true
    branches:
        include:
            - master
            - development
pool:
    vmImage: 'windows-latest'
stages:
    - stage: Build
      jobs:
          - job: Build
            workspace:
                clean: all
            steps:
                - task: ComponentGovernanceComponentDetection@0
                  inputs:
                      scanType: 'Register'
                      verbosity: 'Verbose'
                      alertWarningLevel: 'High'
                      failOnAlert: true
                - task: CredScan@2
                  inputs:
                      toolMajorVersion: 'V2'
                - script: npm install
                  displayName: Install Dependencies
                - script: npm build
                  displayName: Build
                  env:
                      NODE_ENV: production
                - script: npm run ci-test
                  displayName: Run Tests and Coverage
                  timeoutInMinutes: 20
                - task: PublishBuildArtifacts@1
                  displayName: 'Upload NPM cache logs'
                  inputs:
                      pathtoPublish: 'C:\npm\cache\_logs'
                      artifactName: 'npm-logs'
                  condition: failed()
                - task: PublishTestResults@2
                  inputs:
                      testResultsFormat: 'JUnit'
                      testResultsFiles: './junit.xml'
                      mergeTestResults: true
                      failTaskOnFailedTests: true
                      testRunTitle: 'Unit Tests'
                - task: PublishCodeCoverageResults@1
                  inputs:
                      codeCoverageTool: 'Cobertura'
                      summaryFileLocation: 'coverage/cobertura-coverage.xml'
                - task: DeleteFiles@1
                  inputs:
                      SourceFolder: './'
                      Contents: 'junit.xml'
                      RemoveSourceFolder: false
                - task: DeleteFiles@1
                  inputs:
                      SourceFolder: './coverage'
                      Contents: '*'
                      RemoveSourceFolder: true
                - task: DeleteFiles@1
                  inputs:
                      SourceFolder: 'node_modules'
                      Contents: '*'
                      RemoveSourceFolder: true
                - task: ArchiveFiles@2
                  inputs:
                      rootFolderOrFile: './'
                      includeRootFolder: false
                      archiveType: 'zip'
                      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                      replaceExistingArchive: true
                - task: CopyFiles@2
                  inputs:
                      SourceFolder: './deployment'
                      Contents: '**'
                      TargetFolder: '$(Build.ArtifactStagingDirectory)/deployment'
                - task: PublishBuildArtifacts@1
                  displayName: 'Upload Artifact'
                  inputs:
                      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
                      artifactName: 'msteams-app-questionly'
